Contronic/Controllers/ContactSurfaceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using Umbraco.Web.Mvc;


namespace Contronic.Controllers
{
    public class ContactSurfaceController : SurfaceController
    {

        public ActionResult MailSender(string userEmail, string subject, string name, string message)
        {
            MailMessage mail = new MailMessage();

            SmtpClient Smtp = new SmtpClient()
            {
                Host = "smtp.unoeuro.com",
                EnableSsl = true,
                Port = 587,
                Credentials = new NetworkCredential("info@contronic.dk", "6940lemst")
            };

            mail.From = new MailAddress("info@contronic.dk");
            mail.To.Add("info@contronic.dk");
            mail.Subject = "Mail fra Contronic - Kontakt";
            mail.IsBodyHtml = true;

            mail.Body = "Name:" + name +
                "<br /> Mail: " + userEmail +
                "<br /><br />Besked:" + message;

            Smtp.Send(mail);

            return RedirectToUmbracoPage(1052, "status=sent");
        }

        public ActionResult InstalSender(string firm, string phone, string name, string userEmail, string City, string message)
        {
            MailMessage mail = new MailMessage();

            SmtpClient Smtp = new SmtpClient()
            {
                Host = "smtp.unoeuro.com",
                EnableSsl = true,
                Port = 587,
                Credentials = new NetworkCredential("info@contronic.dk", "6940lemst")
            };

            mail.From = new MailAddress(userEmail);
            mail.To.Add("info@contronic.dk");
            mail.Subject = "Mail fra Contronic - Installatør";
            mail.IsBodyHtml = true;
             
            
            mail.Body = "Firma:" + firm +
                "<br /> Navn: " + name +
                "<br /> Telefon: " + phone +
                "<br /> Email: " + userEmail +
                "<br /> Område: " + City +
                "<br /> Mail: " + message;

            Smtp.Send(mail);

            return RedirectToUmbracoPage(1052, "status=sent");
        }
    }
}

Contronic/Views/Datasheets.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.Datasheets>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
    Layout = "Layout.cshtml";
}
<div class="container">
    <div class="row">
        <div class="col-sm-11 col-sm-offset-1">
            <br />
            <h1 class="inst-header text-center">@Umbraco.Field("heading")</h1>
            <p>@Umbraco.Field("txt")</p>

        </div>

    </div>
  
    <div class="row">
       
            @foreach (var datasheet in Model.Content.Children())
            { <div class="col-sm-6">
                <h2> @datasheet.GetPropertyValue("heading")</h2>
                @foreach (var pdf in datasheet.Children())
                {
                <p><a href="@pdf.GetPropertyValue("pdf")">@pdf.GetPropertyValue("heading")</a></p>
                }
            </div>
            }
          
        </div>
    </div>

Contronic/Views/DatasheetsCatecory.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.DatasheetsCatecory>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = null;
}

Contronic/Views/DatasheetsCatecoryChild.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.DatasheetsCatecoryChild>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = null;
}

Contronic/Views/Elearning.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.Elearning>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = "Layout.cshtml";
}

<div class="container">
    <div class="row">
        <div class="col-sm-11 col-sm-offset-1">

            <h1 class="inst-header text-center">@Umbraco.Field("heading")</h1>
            <p>@Umbraco.Field("IntroTxt")</p>

        </div>

    </div>
        <div class="row">
          




            @foreach (var video in Model.Content.Children())
            {
                <div class="col-sm-4">


                    <iframe width="261" height="220" src="@video.GetPropertyValue("video")" frameborder="0" allowfullscreen></iframe>
                <h3>
                    @video.GetPropertyValue("heading")
                </h3>
                <p>
                    @video.GetPropertyValue("text")
                    </p></div>

            }

            <div class="col-sm-4 ">
               
                <div class="col-sm-12 elearning text-center">
                    <br />
                    <a href="~/Concept/story_html5.html"> Concept 2000Xp Elearning</a>
                </div>
                <div class="col-sm-12">
                    <h3>
                        XP moduler
                    </h3>
                    <p>
                        Lær om de enkle XP moduler via E-learning
                    </p>
                    </div>
                </div>



        </div>

    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />

</div>

Contronic/Views/ElearningItem.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.ElearningItem>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = null;
} 

Contronic/Views/Home.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.Home>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = "Layout.cshtml";
    string status = Request.QueryString["status"] != null ? Request.QueryString["status"] : "";
}


<iframe width="1903" height="648" src="https://www.youtube.com/embed/S0mXrDggrnI?rel=0&amp;controls=0&amp;showinfo=0" frameborder="0" allowfullscreen></iframe>
<!-- Main -->
<div id="main-wrapper">
    <div id="main" class="container-fluid">
        <div class="row">
            <div class="col-sm-12 area1">
                <p class="text-center"><b>Salg og Service af </b></p>
                <h1 class="text-center">Conson, Zensehome og Wifi-LED</h1>

            </div>
        </div>
        <div class="row">
            <div class="container bokse">
                <div class="col-sm-3 col-sm-offset-1 Boks text-center">
                    <h3 class="green">@Umbraco.Field("boks1Heading")</h3>
                    <p>@Umbraco.Field("boks1Txt")</p>
                </div>

                <div class="col-sm-3 col-sm-offset-1 Boks text-center">
                    <h3 class="green">@Umbraco.Field("boks2Heading")</h3>
                    <p>@Umbraco.Field("boks2Txt")</p>
                </div>
                <div class="col-sm-3 col-sm-offset-1 Boks text-center">
                    <h3 class="green">@Umbraco.Field("boks3Heading")</h3>
                    <p>@Umbraco.Field("boks3Txt")</p>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12 area2 bg-grey">
                <div class="col-sm-4 col-sm-offset-4">
                    <h2>@Umbraco.Field("textAreaHeading")</h2>
                    <p>@Umbraco.Field("textAreaTxt")</p>
                    <a href="/installatoer/" class="btn btn-success">@Umbraco.Field("textAreaButton")</a>
                </div>
            </div>


        </div>


        <div class="row bg-blue kontakt">
            <h2 class="text-center">Spørgsmål til køb, opsætning eller service? </h2>
            <div class="col-md-4 col-sm-offset-2">

                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2229.587491456179!2d8.377486516109062!3d56.02581607836937!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x464a512150eec885%3A0xea5df6d99828cc6d!2sContronic+ApS!5e0!3m2!1sen!2sdk!4v1457042374396" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
            </div>
            <!-- Contact Details Column -->

            <div class="col-md-4 form">

                <p class="text-center">
                    Contronic Aps <br />
                    Bredgade 21, 6940 Lem st<br />
                    contronic@contronic.dk<br />
                    Tel: +45 97342000 <br />

                
                </p>
                @using (Html.BeginForm("Mailsender", "ContactSurface", FormMethod.Post))
                {
                    @Html.TextBox("name", null, new { @class = "form-control", @placeholder = "Navn" })
                    @Html.TextBox("userEmail", null, new { @class = "form-control", @placeholder = "Email" })
                    @Html.TextBox("subject", null, new { @class = "form-control", @placeholder = "Emne" })
                    @Html.TextArea("message", null, new { @class = "form-control", @placeholder = "Besked" })
                    <button type="submit" class="btn btn-success">Send</button>

                }

              @if (status == "sent")
                {<div class="alert alert-success">
                    Tak for din Mail!
                </div>

                }



            </div>

        </div>
    </div>
</div>

<br /> <br />

<!-- /Main -->

Contronic/Views/Installations.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.Installations>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = "Layout.cshtml";
     string status = Request.QueryString["status"] != null ? Request.QueryString["status"] : "";
}

<div class="container">
    <div class="row">
        <div class="col-sm-11 col-sm-offset-1">

            <h1 class="inst-header text-center">@Umbraco.Field("heading")</h1>
            <p>@Umbraco.Field("text")</p>

        </div>

        <div class="row">

            @foreach (var person in Model.Content.Children())
            {
                <div class="col-sm-2 col-sm-offset-2">
                    <p>
                        @person.GetPropertyValue("firm") <br />
                        @person.GetPropertyValue("navn") <br />
                        @person.GetPropertyValue("number") <br />
                        @person.GetPropertyValue("email") <br />
                        @person.GetPropertyValue("city") <br />
                    </p>
                </div>

            }


        </div>

    </div>
        </div>
        <div class="row bg-blue kontakt">
            <h2 class="text-center">Vil du på listen?</h2>
            <div class="col-md-3 col-sm-offset-3">

               @Umbraco.Field("text2")
            </div>
            <!-- Contact Details Column -->

            <div class="col-md-3 white">
              <b>Udfyld formularen og kom på listen:</b>

                @using (Html.BeginForm("InstalSender", "ContactSurface", FormMethod.Post))
                {
                    @Html.TextBox("firm", null, new { @class = "form-control", @placeholder = "Firma" })
                    @Html.TextBox("name", null, new { @class = "form-control", @placeholder = "Navn" })
                    @Html.TextBox("phone", null, new { @class = "form-control", @placeholder = "Telefon" })
                    @Html.TextBox("userEmail", null, new { @class = "form-control", @placeholder = "Email" })
                    @Html.TextBox("City", null, new { @class = "form-control", @placeholder = "By" })
                    @Html.TextArea("message", null, new { @class = "form-control", @placeholder = "Besked" })
                    <button type="submit" class="btn btn-success">Send</button>

                }

              @if (status == "sent")
                {<div class="alert alert-success">
                    Tak for din Mail!
                </div>

                }


                <br /><br /><br />
            </div>

        </div> 

Contronic/Views/InstallationsItem.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.InstallationsItem>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = null;
}

Contronic/Views/Kontakt.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.Kontakt>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
    Layout = "Layout.cshtml";

    string status = Request.QueryString["status"] != null ? Request.QueryString["status"] : "";
}
@{
    if (IsPost)
    {
        <div class="alert alert-success alert-dismissible" role="alert">
            <button type="button" class="close" data-dissmiss="alert" aria-label="Close"></button>
        </div>
    }
}

<div class="row">

    <h1 class="text-center inst-header">Spørgsmål til køb, opsætning eller service? </h1>
    <div class="col-md-4 col-sm-offset-2">

        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2229.587491456179!2d8.377486516109062!3d56.02581607836937!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x464a512150eec885%3A0xea5df6d99828cc6d!2sContronic+ApS!5e0!3m2!1sen!2sdk!4v1457042374396" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
    </div>
    <!-- Contact Details Column -->

    <div class="col-md-4 form">

        <p class="text-center">
            Contronic Aps <br />
            Bredgade 21, 6940 Lem st<br />
            contronic@contronic.dk<br />
            Tel: +45 97342000 <br />
       </p>
@using (Html.BeginForm("Mailsender", "ContactSurface", FormMethod.Post))
{
    @Html.TextBox("name", null, new { @class = "form-control", @placeholder = "Navn" })
    @Html.TextBox("userEmail", null, new { @class = "form-control", @placeholder = "Email" })
    @Html.TextBox("subject", null, new { @class = "form-control", @placeholder = "Emne" })
    @Html.TextArea("message", null, new { @class = "form-control", @placeholder = "Besked" })
    <button type="submit" class="btn btn-success">Send</button>

}

@if (status == "sent")
{<div class="alert alert-success">
        Tak for din Mail!
    </div>

}

        @*<form method="post">
            <div class="form-group">
          
                <input type="text" class="form-control" required id="name" name="name" placeholder="Navn" />

            </div>

            <div class="form-group">
       
                <input type="text" class="form-control" required id="email" name="email" placeholder="Email" />

            </div>

            <div class="form-group">

                <textarea type="text" rows="8" id="message" required class="form-control" name="message" placeholder="Besked"></textarea>
            </div>
            <button type="submit" class="btn btn-default">Send besked</button>

        </form>*@
















        @*@if (status == "sent")
            {<div class="alert alert-success">
                Tak for din Mail!
            </div>

            }*@



    </div>

</div>

Contronic/Views/Layout.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.Layout>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
    Layout = null;
}

<!DOCTYPE html>
<!--
    TXT 2.0 by HTML5 UP
    html5up.net | twitter.com/n33co
    Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
<head>
    <title>@Umbraco.Field("title", altFieldAlias: "pageName") | Contronic</title>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <link rel="shortcut icon" href="/Content/contronicminiicon.png" />

    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="author" content="Contronic">


    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/css/Style.css" rel="stylesheet" />




    <script src="~/Scripts/jquery-1.9.1.min.js"></script>

    <script src="~/Scripts/bootstrap.js"></script>
    <!--[if lte IE 9]><link rel="stylesheet" href="/css/ie9.css" /><![endif]-->
    <!--[if lte IE 8]><script src="/js/html5shiv.js"></script><link rel="stylesheet" href="/css/ie8.css" /><![endif]-->
    <!--[if lte IE 7]><link rel="stylesheet" href="/css/ie7.css" /><![endif]-->
</head>
<body class="homepage">

    @Umbraco.RenderMacro("Navigation")

    @RenderBody()
    <!-- Footer -->


            <footer id="footer" class="col-sm-12">


                <!-- Copyright -->
                <div id="copyright" class="col-sm-12 text-center white">
                    &copy; @DateTime.Now.Year | Contronic | Bredgade 21 - 6940 Lem st. | Tlf. 97342000 | contronic@contronic.dk
                </div>
                <!-- /Copyright -->

            </footer>
     
    <script>
    (function (i, s, o, g, r, a, m) {
        i['GoogleAnalyticsObject'] = r; i[r] = i[r] || function () {
            (i[r].q = i[r].q || []).push(arguments)
        }, i[r].l = 1 * new Date(); a = s.createElement(o),
        m = s.getElementsByTagName(o)[0]; a.async = 1; a.src = g; m.parentNode.insertBefore(a, m)
    })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

    ga('create', 'UA-71074289-1', 'auto');
    ga('send', 'pageview');

    </script> 
</body>
</html>

Contronic/Views/MacroPartials/Navigation.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage


@*
    This snippet displays a list of links of the pages immediately under the top-most page in the content tree.
    This is the home page for a standard website.
    It also highlights the current active page/section in the navigation with the css class "current".
*@
@{
    // Model.Content is the current page that we're on
    // AncestorsOrSelf is all of the ancestors this page has in the tree
    // (1) means: go up to level 1 and stop looking for more ancestors when you get there
    // First() gets the first ancestor found (the home page, on level 1)
    var homePage = CurrentPage.AncestorsOrSelf(1).First();

    // The menu items we want are all of the children of the homepage
    // We also check if "Hide in navigation" is on in the menu, we shouldn't show hidden items
    var menuItems = homePage.Children.Where("hideInNavigation == false");
}


<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/"><img class="img-responsive logo" src="/Content/ContronicLogo.png" /></a>

        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                @* If the Url of the current page is "/" then we want to add the class "current_page_item" *@
                @* Otherwise, we set the class to null, that way it will not even be added to the
                    <li> element *@
             

                @foreach (var item in menuItems)
                {
                    @* If the Id of the item is the same as the Id of the current page then we want to add the class "current_page_item" *@
                    @* Otherwise, we set the class to null, that way it will not even be added to the
                        <li> element *@
                    <li class="@(CurrentPage.Id == item.Id ? " current_page_item":
                    null)"><a href="@item.Url">@item.Name</a></li>
                }




            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>

Contronic/Views/News.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.News>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
    Layout = "Layout.cshtml";
}

<div class="container">

    <div class="row">
        <h1 class="page-header">
            @Model.Content.GetPropertyValue("heading")

        </h1>
        @foreach (var newsitem in Model.Content.Children())
        {
            <div class="col-sm-12">



                <!-- First Blog Post -->
                <h2>
                    <a href="@newsitem.Url">@newsitem.GetPropertyValue("heading")</a>
                </h2>
                <p class="lead">
                    by <a href="@newsitem.Url">Arne Lund Mogensen</a>
                </p>
                <p><span class="glyphicon glyphicon-time"></span> Posted on @newsitem.CreateDate </p>
            
                
                <hr>
                <p>@Umbraco.Truncate(newsitem.GetPropertyValue("text").ToString(), 250)</p>
                <a class="btn btn-primary" href="@newsitem.Url">Læs mere <span class="glyphicon glyphicon-chevron-right"></span></a>

                <hr>




            </div>
        }
        <!-- Blog Entries Column -->


    </div>

</div>

Contronic/Views/NewsItem.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.NewsItem>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = "Layout.cshtml";
}

 <!-- Page Content -->
<div class="container">
    <div class="row">
        <h1 class="page-header">
            @Model.Content.GetPropertyValue("heading")

        </h1>
      
        <!-- Author -->
        <p class="lead">
            by Arne Lund Mogensen
        </p>

        <hr>

        <!-- Date/Time -->
        <p><span class="glyphicon glyphicon-time"></span> Posted on @Model.Content.CreateDate</p>
        <hr>

        <!-- Post Content -->
        <p class="lead"> @Model.Content.GetPropertyValue("text")   </div>
</div>
</div>

Contronic/Views/Partials/Grid/Bootstrap2.cshtml
@inherits UmbracoViewPage<dynamic>
@using Umbraco.Web.Templates
@using Newtonsoft.Json.Linq

@* 
    Razor helpers located at the bottom of this file
*@

@if (Model != null && Model.sections != null)
{
    var oneColumn = ((System.Collections.ICollection)Model.sections).Count == 1;
    
    <div class="umb-grid">
        @if (oneColumn)
        {
            foreach (var section in Model.sections) {
                <div class="grid-section">
                    @foreach (var row in section.rows) {
                        @renderRow(row, true);
                    }
                </div>
            }   
        }else { 
            <div class="container">
                <div class="row clearfix">
                    @foreach (var s in Model.sections) {
                        <div class="grid-section">
                            <div class="@("span" + s.grid) column">
                                @foreach (var row in s.rows) {
                                    @renderRow(row, false);
                                }
                            </div>
                        </div>
                    }
                </div>
            </div>   
        }
    </div>
}

@helper renderRow(dynamic row, bool singleColumn){
    <div @RenderElementAttributes(row)>
        @Umbraco.If(singleColumn, "<div class='container'>")
        <div class="row clearfix">
            @foreach ( var area in row.areas ) {
            <div class="@("span" + area.grid) column">
                <div @RenderElementAttributes(area)>
                    @foreach (var control in area.controls) {
                        if (control !=null && control.editor != null && control.editor.view != null ) {
                            <text>@Html.Partial("grid/editors/base", (object)control)</text>
                        }
                    }
                </div>
            </div>}
        </div>
        @Umbraco.If(singleColumn, "</div>")
    </div>
}

@functions {
    public static MvcHtmlString RenderElementAttributes(dynamic contentItem)
    {
        var attrs = new List<string>();
        JObject cfg = contentItem.config;

        if(cfg != null)
            foreach (JProperty property in cfg.Properties()) {
                attrs.Add(property.Name + "=\"" + property.Value.ToString() + "\"");
            }
                
        JObject style = contentItem.styles;

        if (style != null) { 
        var cssVals = new List<string>();
        foreach (JProperty property in style.Properties())
            cssVals.Add(property.Name + ":" + property.Value.ToString() + ";");

        if (cssVals.Any())
            attrs.Add("style=\"" + string.Join(" ", cssVals) + "\"");
        }
            
        return new MvcHtmlString(string.Join(" ", attrs));
    }
}

Contronic/Views/Partials/Grid/Bootstrap3.cshtml
@inherits UmbracoViewPage<dynamic>
@using Umbraco.Web.Templates
@using Newtonsoft.Json.Linq

@* 
    Razor helpers located at the bottom of this file
*@

@if (Model != null && Model.sections != null)
{
    var oneColumn = ((System.Collections.ICollection)Model.sections).Count == 1;
    
    <div class="umb-grid">
        @if (oneColumn)
        {
            foreach (var section in Model.sections) {
                <div class="grid-section">
                    @foreach (var row in section.rows) {
                        @renderRow(row, true);
                    }
                </div>
            }   
        }else { 
            <div class="container">
                <div class="row clearfix">
                    @foreach (var s in Model.sections) {
                        <div class="grid-section">
                            <div class="col-md-@s.grid column">
                                @foreach (var row in s.rows) {
                                    @renderRow(row, false);
                                }
                            </div>
                        </div>
                    }
                </div>
            </div>   
        }
    </div>
}

@helper renderRow(dynamic row, bool singleColumn){
    <div @RenderElementAttributes(row)>
        @Umbraco.If(singleColumn, "<div class='container'>")
        <div class="row clearfix">
            @foreach ( var area in row.areas ) {
            <div class="col-md-@area.grid column">
                <div @RenderElementAttributes(area)>
                    @foreach (var control in area.controls) {
                        if (control !=null && control.editor != null && control.editor.view != null ) {
                            <text>@Html.Partial("grid/editors/base", (object)control)</text>
                        }
                    }
                </div>
            </div>}
        </div>
        @Umbraco.If(singleColumn, "</div>")
    </div>
}

@functions {
    public static MvcHtmlString RenderElementAttributes(dynamic contentItem)
    {
        var attrs = new List<string>();
        JObject cfg = contentItem.config;

        if(cfg != null)
            foreach (JProperty property in cfg.Properties()) {
                attrs.Add(property.Name + "=\"" + property.Value.ToString() + "\"");
            }
                
        JObject style = contentItem.styles;

        if (style != null) { 
        var cssVals = new List<string>();
        foreach (JProperty property in style.Properties())
            cssVals.Add(property.Name + ":" + property.Value.ToString() + ";");

        if (cssVals.Any())
            attrs.Add("style=\"" + string.Join(" ", cssVals) + "\"");
        }
            
        return new MvcHtmlString(string.Join(" ", attrs));
    }
}

Contronic/Views/Partials/Grid/Editors/Base.cshtml
@model dynamic
@using Umbraco.Web.Templates

@functions {
    public static string EditorView(dynamic contentItem)
    {
        string view = contentItem.editor.render != null ? contentItem.editor.render.ToString() : contentItem.editor.view.ToString();
        view = view.ToLower().Replace(".html", ".cshtml");
        
        if (!view.Contains("/")) {
            view = "grid/editors/" + view;
        }

        return view;
    }
}
@try
{
    string editor = EditorView(Model);                                                       
    <text>@Html.Partial(editor, (object)Model)</text>
}
catch (Exception ex) { 
<pre>@ex.ToString()</pre>
}

Contronic/Views/Partials/Grid/Editors/Embed.cshtml
@model dynamic
@using Umbraco.Web.Templates
@Html.Raw(Model.value)

Contronic/Views/Partials/Grid/Editors/Macro.cshtml
@inherits UmbracoViewPage<dynamic>
@using Umbraco.Web.Templates


@if (Model.value != null)
{
    string macroAlias = Model.value.macroAlias.ToString();
    ViewDataDictionary parameters = new ViewDataDictionary();
    foreach (dynamic mpd in Model.value.macroParamsDictionary)
    {
        parameters.Add(mpd.Name, mpd.Value);
    }

    <text>
        @Umbraco.RenderMacro(macroAlias, parameters)
    </text>
}

Contronic/Views/Partials/Grid/Editors/Media.cshtml
@model dynamic
@using Umbraco.Web.Templates

@if (Model.value != null)
{   
    var url = Model.value.image;
    if(Model.editor.config != null && Model.editor.config.size != null){
        url += "?width=" + Model.editor.config.size.width;
        url += "&height=" + Model.editor.config.size.height;

        if(Model.value.focalPoint != null){
            url += "&center=" + Model.value.focalPoint.top +"," + Model.value.focalPoint.left;
            url += "&mode=crop";
        }
    }
    
    <img src="@url" alt="@Model.value.altText">
    
    if (Model.value.caption != null)
    {
        <p class="caption">@Model.value.caption</p>
    }
}

Contronic/Views/Partials/Grid/Editors/Rte.cshtml
@model dynamic
@using Umbraco.Web.Templates

@Html.Raw(TemplateUtilities.ParseInternalLinks(Model.value.ToString()))

Contronic/Views/Partials/Grid/Editors/Textstring.cshtml
@model dynamic
@using Umbraco.Web.Templates

@if (Model.editor.config.markup != null)
{
    string markup = Model.editor.config.markup.ToString();

    markup = markup.Replace("#value#", Model.value.ToString());
    markup = markup.Replace("#style#", Model.editor.config.style.ToString());

    <text>
        @Html.Raw(markup)
    </text>
}
else
{
    <text>
        <div style="@Model.editor.config.style">@Model.value</div>
    </text>
}

Contronic/Views/ProdukterItem.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.ProdukterItem>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = null;
}